# Generated by Django 4.0.4 on 2022-05-30 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('member_since', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
                'db_table': 'Lodge_guest',
            },
        ),
        migrations.CreateModel(
            name='Lodge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('lodgeRoomInfo', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Lodge',
                'db_table': 'Lodge',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodge_app.guest')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateTimeField()),
                ('date_out', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodge_app.guest')),
                ('staff_activated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Lodge_reservation',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodge_app.lodge')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'Lodge_room',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_name', models.CharField(max_length=100)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodge_app.guest')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodge_app.payment')),
            ],
            options={
                'db_table': 'Lodge_transaction',
            },
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/%Y/%m/%d')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodge_app.room')),
                ('user_uploaded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Lodge_room_photos',
            },
        ),
        migrations.CreateModel(
            name='ReservedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodge_app.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodge_app.room')),
            ],
            options={
                'verbose_name': 'Rerseved Room',
                'verbose_name_plural': 'Reserved Rooms',
                'db_table': 'Lodge_reserved_room',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodge_app.lodge')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'db_table': 'Lodge_policy',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image', models.ImageField(upload_to='menuimages/%Y/%m/%d')),
                ('category', models.CharField(choices=[('Vegeterian', 'Vegiterian menus'), ('Non Vegeterian Menu', 'Non Vegeterian menus')], max_length=50)),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodge_app.lodge')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'db_table': 'Lodge_menu',
            },
        ),
        migrations.CreateModel(
            name='LodgePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('BEDROOM', 'Bedroom'), ('OTHER', 'Other'), ('BUILDING', 'Building'), ('LOBBY', 'Lobby')], default='BEDROOM', max_length=25)),
                ('image', models.ImageField(upload_to='')),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodge_app.lodge')),
            ],
            options={
                'verbose_name': 'Lodge Photo',
                'verbose_name_plural': 'Lodge photos',
                'db_table': 'Lodge_photo',
            },
        ),
        migrations.CreateModel(
            name='LodgeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('lodge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lodge_app.lodge')),
                ('nearbyLocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lodge_app.lodgelocation')),
            ],
            options={
                'verbose_name': 'Lodge Location',
                'verbose_name_plural': 'Lodge locations',
                'db_table': 'Lodge_location',
            },
        ),
        migrations.CreateModel(
            name='Freebie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodge_app.lodge')),
            ],
            options={
                'verbose_name': 'freebie',
                'verbose_name_plural': 'freebies',
                'db_table': 'Lodge_freebie',
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('faIcon', models.CharField(max_length=50)),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodge_app.lodge')),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'db_table': 'Lodge_amenity',
            },
        ),
    ]
