# Generated by Django 4.0.5 on 2022-06-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge_app', '0003_reservation_rerservation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='rerservation_code',
            field=models.IntegerField(null=True),
        ),
    ]
