# Generated by Django 4.0.5 on 2022-06-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge_app', '0004_alter_reservation_rerservation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='rooms_images/%Y/%m/%d/'),
        ),
    ]
