# Generated by Django 4.0.5 on 2022-06-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge_app', '0006_room_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='published',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
