# Generated by Django 4.0.5 on 2022-06-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge_app', '0008_alter_amenity_faicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='faIcon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
