# Generated by Django 4.0.5 on 2022-06-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodge_app', '0009_alter_amenity_faicon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='staff_activated',
            new_name='user',
        ),
    ]
