# Generated by Django 4.0.5 on 2022-06-05 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodge_app', '0010_rename_staff_activated_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lodge_app.room'),
        ),
    ]
