# Generated by Django 4.0.5 on 2022-06-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodge_app', '0011_reservation_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='active',
            new_name='canceled',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='rejected',
            new_name='comfirmed',
        ),
    ]
