# Generated by Django 4.0.5 on 2022-06-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge_app', '0013_alter_reservation_date_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_out',
            field=models.DateTimeField(null=True),
        ),
    ]
