# Generated by Django 4.0.5 on 2022-06-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge_app', '0015_remove_reservation_user_reservation_staff_activated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_in',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_out',
            field=models.DateField(null=True),
        ),
    ]
