# Generated by Django 4.0.5 on 2022-06-05 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodge_app', '0016_alter_reservation_date_in_alter_reservation_date_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomphoto',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='lodge_app.room'),
        ),
    ]
