# Generated by Django 4.0.5 on 2022-06-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge_app', '0018_room_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='rerservation_code',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
