# Generated by Django 4.0.5 on 2022-06-06 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodge_app', '0021_room_room_menitiest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_menitiest',
            new_name='room_amenitiest',
        ),
    ]
