# Generated by Django 4.0.5 on 2022-06-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodge_app', '0022_rename_room_menitiest_room_room_amenitiest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_amenitiest',
        ),
    ]
