# Generated by Django 4.0.5 on 2022-06-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge_app', '0023_remove_room_room_amenitiest'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
