# Generated by Django 4.0.5 on 2022-06-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge_app', '0026_guest_user_alter_reservation_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
