# Generated by Django 4.0.5 on 2022-06-10 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodge_app', '0027_amenity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='lodge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='lodge_app.lodge'),
        ),
    ]
